import type { Metadata } from "next";
import { Onest, Abhaya_Libre } from "next/font/google";
import "./globals.css";

const abhayaLibre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: '--font-abhaya-libre'
});


const onest = Onest({
  subsets:["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-onest'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} ${abhayaLibre.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}